### PR TITLE
Added support to "automatically" chose between a and an

### LINKED ISSUE #23: Select "a" or "an" automatically
Depending on whether it's the first use or not, either only the abbreviation or the full text is shown.
When #11 is fixed, this will become an issue with "a" and "an" before the abbrevation when using the "Long Form (LF)" option. I have made the modification suggested in #11 in my local instance already and that is causing issues in the following constellation:

`An @fir filter` can translate into "An FIR filter" (correct) or, on first use, to "An Finite Impulse Response (FIR) filter" (which is wrong).

What would be good here is a way to add the correct choice of "a" or "an" automatically.
I'm not quite sure how this can be implemented, though. What I imagine ist that it might look something like `@[a]fir` and then this is done automatically. Though there _might_ be cases where you need to explicitly specifiy whether to use "a" or "an" for the long and short form...

### PR DESCRIPTION
**Pull request by St0wy**
Fixes #23 

I added two new fields on the glossary entries : `artshort` and `artlong`. They're both here so that it can be specified if "a" or "an" is needed. They default to "a".

To use it, you can call `#agls("key")` and it will use the correct article. I havent defined one for plurals (plus it would make more sense to do that once/if #33 is merged) since in english you generally just use the word without an article. But it could be usefull to add that feature for other languages (like French for example). Tell me if you think that could be usefull and I'll add it to the PR.

### CODE REVIEW

**Comment by slashformotion** [comment]
LGTM.

**Comment by slashformotion** [comment]
The plurals MR is merged, perhaps 'a'/'an' support could be directly included into the gls / glspl functions. what do you think ?

**Comment by slashformotion** [comment]
just a heads up, I will release the plurals support and then this one

**Comment by St0wy** [comment]
Maybe it could be added to `gls` with a parameter like `show_article` that would default to false, but I think there's some value on having a similar API to what's available in LaTeX. But if you have a strong preference for having it inside `gls` I could change my PR to be like that

**Comment by slashformotion** [comment]
let's keep "agls" and see what users thinks

**Pull request merged**
