### PR TITLE
Groups for entries

### PR DESCRIPTION
**Pull request by indicatelovelace**
I currently have so many entries that it's useful to group them.
No breaking changes.

### CODE REVIEW

**Comment by slashformotion** [comment]
using context would break compatibility with older versions of the container, so I don't know about this

**Comment by indicatelovelace** [comment]
Of course, but locate is going to be unsupported in the future. Package authors should adapt. Also 0.11 is backwards compatible with 0.10, so there is no reason to use 0.10 instead of 0.11. Also one can use a specific package version of glossarium.

**Comment by slashformotion** [comment]
This is awkward: for some reason the ci pass but i can't compile the "full-example" locally. It fails with this error :
image

**Comment by slashformotion** [comment]
I am merging this and finding out why it doesn't work later. Thanks for your contribution @indicatelovelace

**Pull request merged**
